export const atomic_data=[
    {symbol: 'H', atomic_number: 1, ionizationE: 1312, electron_config: [1]},
    {symbol: 'He', atomic_number: 2, ionizationE: 2372.3, electron_config: [2]},
    {symbol: 'Li', atomic_number: 3, ionizationE: 520.2},
    {symbol: 'Be', atomic_number: 4, ionizationE: 899.5},  
    {symbol: 'B', atomic_number: 5, ionizationE: 800.6},  
    {symbol: 'C', atomic_number: 7, ionizationE: 1402.3},  
    {symbol: 'N', atomic_number: 6, ionizationE: 1086.5},  
    {symbol: 'O', atomic_number: 8, ionizationE: 1313.9},  
    {symbol: 'F', atomic_number: 9, ionizationE: 1681},  
    {symbol: 'Ne', atomic_number: 10, ionizationE: 2080.7},  
    {symbol: 'Na', atomic_number: 11, ionizationE: 495.8},  
    {symbol: 'Mg', atomic_number: 12, ionizationE: 737.7},
    {symbol: 'Al', atomic_number: 13, ionizationE: 577.5},
    {symbol: 'Si', atomic_number: 14, ionizationE: 786.5},
    {symbol: 'P', atomic_number: 15, ionizationE: 1011.8},
    {symbol: 'S', atomic_number: 16, ionizationE: 999.6},
    {symbol: 'Cl', atomic_number: 17, ionizationE: 1251.2},
    {symbol: 'Ar', atomic_number: 18, ionizationE: 1520.6},
    {symbol: 'K', atomic_number: 19, ionizationE: 418.8},
    {symbol: 'Ca', atomic_number: 20, ionizationE: 589.8},
    {symbol: 'Sc', atomic_number: 21, ionizationE: 633.1},
    {symbol: 'Ti', atomic_number: 22, ionizationE: 658.8},
    {symbol: 'V', atomic_number: 23, ionizationE: 650.9},
    {symbol: 'Cr', atomic_number: 24, ionizationE: 652.9},
    {symbol: 'Mn', atomic_number: 25, ionizationE: 658.8},
    {symbol: 'Fe', atomic_number: 26, ionizationE: 658.8},
    {symbol: 'Co', atomic_number: 27, ionizationE: 658.8},
    {symbol: 'Ni', atomic_number: 28, ionizationE: 658.8},
    {symbol: 'Cu', atomic_number: 29, ionizationE: 658.8},
    {symbol: 'Zn', atomic_number: 30, ionizationE: 658.8},
    {symbol: 'Ga', atomic_number: 31, ionizationE: 658.8},
    {symbol: 'Ge', atomic_number: 32, ionizationE: 658.8},
    {symbol: 'As', atomic_number: 33, ionizationE: 658.8},
    {symbol: 'Se', atomic_number: 34, ionizationE: 658.8},
    {symbol: 'Br', atomic_number: 35, ionizationE: 658.8},
    {symbol: 'Kr', atomic_number: 36, ionizationE: 658.8},
    {symbol: 'Rb', atomic_number: 37, ionizationE: 658.8},
    {symbol: 'Sr', atomic_number: 38, ionizationE: 658.8},
    {symbol: 'Y', atomic_number: 39, ionizationE: 658.8},
    {symbol: 'Zr', atomic_number: 40, ionizationE: 658.8},

    

]